volumes:
  gradle-cache:
  pg-data:

services:
  db:
    image: postgres:14.8-alpine
    container_name: jdbc_postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./src/main/resources/initdb:/docker-entrypoint-initdb.d
    expose:
      - 5432
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=$SPRING_DATASOURCE_PASSWORD
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
      - PGDATA=/var/lib/postgresql/data/pg-data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  builder:
    image: gradle:8.11.1-jdk17-jammy
    container_name: jdbc_builder
    working_dir: /app
    volumes:
      - .:/app
      - gradle-cache:/root/.gradle
    command: gradle bootJar --stacktrace

  app:
    image: openjdk:17-jdk-slim
    container_name: jdbc_app
    depends_on:
      builder:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DB_HOST=db
    ports:
      - "8080:8080"
    command: java -jar build/libs/app.jar
    restart: always
